Делаем get запрос за базой данный для карточек
```js
const getResource = async (url) => {
	const res = await fetch(url);
	if (!res.ok) {
	throw new Error(
	`Could not fetch ${url}, status ${res.status}`);
	}
	return await res.json();
};
```

Fetch возвращает промисс. Промис есть catch на случай ошибки. И тут проблемма. Для Fetch проблема только осутствие интернета, или не возможность произвести запрос. То есть отсутствие сервера или данный его не смутит, он нормально отработает, но пользователь ничего не получит. 404. 
Для решение обратимся к свойствам ответа:
- `res.ok` - boolean, все хорошо?
- `res.status` - номер статуса
 
new Error — создание объекта ошибки
throw  — выкидывает этот объект в catch



https://learn.javascript.ru/destructuring-assignment